version: 1.0.{build}
branches:
  only:
  - master
  - /.*-criteo.*/
image: Visual Studio 2015
init:
- git config --global core.autocrlf true
configuration:
- Release
environment:
  image_flag: 2017
build_script: criteo_build.cmd
on_failure:
- ps: Get-ChildItem .\bin\logs\*.log | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
artifacts:
- path: '**\*.nupkg'
